In [1]:
import torch

In [2]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)

In [3]:
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

In [4]:
y.backward()

In [5]:
print(f'dy/dx: {x.grad}')
print(f'dy/dw: {w.grad}')
print(f'dy/db: {b.grad}')

dy/dx: None
dy/dw: 3.0
dy/db: 1.0


# Numpy

Pytorch with numpy

In [6]:
import numpy as np

In [7]:
x = np.array([[1., 2.], [3., 4.]])
x

array([[1., 2.],
       [3., 4.]])

Torch from_numpy function use the same space memory that the numpy array

In [8]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

Torch tensor will create a copy

In [9]:
z = torch.tensor(x)
z

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [10]:
y *= 2

We can see x and y changes its values, but z remains

In [11]:
x, y, z

(array([[2., 4.],
        [6., 8.]]),
 tensor([[2., 4.],
         [6., 8.]], dtype=torch.float64),
 tensor([[1., 2.],
         [3., 4.]], dtype=torch.float64))

In [12]:
x.dtype, y.dtype, z.dtype

(dtype('float64'), torch.float64, torch.float64)

In [13]:
w = y.numpy()
w

array([[2., 4.],
       [6., 8.]])