In [1]:
import torch

In [2]:
t1 = torch.tensor(10.)
t1

tensor(10.)

In [3]:
t1.dtype

torch.float32

In [4]:
t2 = torch.tensor([1., 2, 3, 4])
t2

tensor([1., 2., 3., 4.])

In [5]:
t2.dtype

torch.float32

In [6]:
t3 = torch.tensor([1, 2, 3, 4])
t3

tensor([1, 2, 3, 4])

In [7]:
t3.dtype

torch.int64

In [8]:
t4 = torch.tensor([
  [
    [1., 2, 3],
    [4, 5, 6]
  ],
  [
    [7, 8, 9],
    [10, 11, 12]
  ]
])
t4

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]]])

In [9]:
t4.dtype

torch.float32

In [10]:
t1.shape

torch.Size([])

In [11]:
t2.shape

torch.Size([4])

In [12]:
t3.shape

torch.Size([4])

In [13]:
t4.shape

torch.Size([2, 2, 3])